[tool.briefcase]
project_name = "Our App"
bundle = "com.example"
version = "0.0.1"
url = "https://example.com/ourapp"
license = "BSD license"
author = 'Shaira Alam'
author_email = "salam13@asu.edu"

[tool.briefcase.app.ourapp]
formal_name = "Our App"
description = "Founders Lab Mobile App"
icon = "src/ourapp/resources/ourapp"
sources = ['src/ourapp']
requires = [
]


[tool.briefcase.app.ourapp.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev38',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.ourapp.linux]
requires = [
    'toga-gtk>=0.3.0.dev38',
]

[tool.briefcase.app.ourapp.linux.appimage]
system_requires = [
    'gir1.2-webkit-3.0',
    'libcairo2-dev',
    'libgirepository1.0-dev',
    'libgtk-3-dev',
    'libpango1.0-dev',
    'librsvg2-dev',
    'libwebkitgtk-3.0-0',
]
linuxdeploy_plugins = [
    'DEPLOY_GTK_VERSION=3 gtk',
]

[tool.briefcase.app.ourapp.linux.flatpak]
flatpak_runtime = 'org.gnome.Platform'
flatpak_runtime_version = '42'
flatpak_sdk = 'org.gnome.Sdk'

[tool.briefcase.app.ourapp.windows]
requires = [
    'toga-winforms>=0.3.0.dev38',
]

# Mobile deployments
[tool.briefcase.app.ourapp.iOS]
requires = [
    'toga-iOS>=0.3.0.dev38',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.ourapp.android]
requires = [
    'toga-android>=0.3.0.dev38'
]

[tool.briefcase.app.ourapp.web]
requires = [
    'toga-web>=0.3.0.dev38'
]
style_framework = "Bootstrap v4.6"
